/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MapEditor {
    }
    interface StickTank {
    }
}
declare global {
    interface HTMLMapEditorElement extends Components.MapEditor, HTMLStencilElement {
    }
    var HTMLMapEditorElement: {
        prototype: HTMLMapEditorElement;
        new (): HTMLMapEditorElement;
    };
    interface HTMLStickTankElement extends Components.StickTank, HTMLStencilElement {
    }
    var HTMLStickTankElement: {
        prototype: HTMLStickTankElement;
        new (): HTMLStickTankElement;
    };
    interface HTMLElementTagNameMap {
        "map-editor": HTMLMapEditorElement;
        "stick-tank": HTMLStickTankElement;
    }
}
declare namespace LocalJSX {
    interface MapEditor {
    }
    interface StickTank {
    }
    interface IntrinsicElements {
        "map-editor": MapEditor;
        "stick-tank": StickTank;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "map-editor": LocalJSX.MapEditor & JSXBase.HTMLAttributes<HTMLMapEditorElement>;
            "stick-tank": LocalJSX.StickTank & JSXBase.HTMLAttributes<HTMLStickTankElement>;
        }
    }
}
